export const NOT_STARTED = Symbol('NOT_STARTED');
export const START_SCREEN = Symbol('START_SCREEN');
export const PLAYER_TURN_START_SCREEN = Symbol('PLAYER_TURN_START_SCREEN');
export const WAITING_FOR_PLAYER_INPUT = Symbol('WAITING_FOR_PLAYER_INPUT');
export const ANIMATING_PLAYER_MOVEMENT = Symbol('ANIMATING_PLAYER_MOVEMENT');
export const ANIMATING_RANDOM_PLAYER_MOVEMENT = Symbol(
    'ANIMATING_RANDOM_PLAYER_MOVEMENT',
);
export const NOTIFY_COLLISION = Symbol('NOTIFY_COLLISION');
export const NOTIFY_AI_COLLISION = Symbol('NOTIFY_AI_COLLISION');
export const NOTIFY_GROUNDED = Symbol('NOTIFY_GROUNDED');
export const NOTIFY_VICTORY = Symbol('NOTIFY_VICTORY');
export const NOTIFY_HIGH_SCORE = Symbol('NOTIFY_HIGH_SCORE');
export const SHOW_MENU = Symbol('SHOW_MENU');
export const AI_THINKING_SCREEN = Symbol('AI_THINKING_SCREEN');
